// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVTM6IK2mGs3J64Br4YQPPH05L9LMVaBM',
    appId: '1:431989975790:web:c32b9c389357b9535e61ff',
    messagingSenderId: '431989975790',
    projectId: 'job-finder-app-facaf',
    authDomain: 'job-finder-app-facaf.firebaseapp.com',
    storageBucket: 'job-finder-app-facaf.firebasestorage.app',
    measurementId: 'G-DJ27X9C1DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPfwx5l4iKM0nvGV-H7xBqcrkfoQs-ET0',
    appId: '1:431989975790:android:aac585fdff123bd95e61ff',
    messagingSenderId: '431989975790',
    projectId: 'job-finder-app-facaf',
    storageBucket: 'job-finder-app-facaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBnB-0yZ8subgAWx1GrtWxPJDapqoFFZc',
    appId: '1:431989975790:ios:e37802990a33fe225e61ff',
    messagingSenderId: '431989975790',
    projectId: 'job-finder-app-facaf',
    storageBucket: 'job-finder-app-facaf.firebasestorage.app',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBnB-0yZ8subgAWx1GrtWxPJDapqoFFZc',
    appId: '1:431989975790:ios:e37802990a33fe225e61ff',
    messagingSenderId: '431989975790',
    projectId: 'job-finder-app-facaf',
    storageBucket: 'job-finder-app-facaf.firebasestorage.app',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVTM6IK2mGs3J64Br4YQPPH05L9LMVaBM',
    appId: '1:431989975790:web:36e63090bc6a07755e61ff',
    messagingSenderId: '431989975790',
    projectId: 'job-finder-app-facaf',
    authDomain: 'job-finder-app-facaf.firebaseapp.com',
    storageBucket: 'job-finder-app-facaf.firebasestorage.app',
    measurementId: 'G-6ZF14XSESE',
  );
}
